Implement PR6423 by using one token of lookahead to disambiguate an *almost* always incorrect case.  This only does the lookahead in the insanely unlikely case, so it shouldn't impact performance.
On this testcase:

struct foo {
}
typedef int x;

Before:

t.c:3:9: error: cannot combine with previous 'struct' declaration specifier
typedef int x;
        ^

After:

t.c:2:2: error: expected ';' after struct
}
 ^
 ;



git-svn-id: https://llvm.org/svn/llvm-project/cfe/trunk@97403 91177308-0d34-0410-b5e6-96231b3b80d8